// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mcbwgabyvtqjzpuvxgui.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jYndnYWJ5dnRxanpwdXZ4Z3VpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc4MTcxNzAsImV4cCI6MjA5MzM5MzE3MH0.ZHsqQ0oh7t654xbhraKar1FSkB5llEabYgC1GZd7jX8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});